# Generated by Django 4.0.4 on 2022-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=2000)),
                ('bio', models.TextField(max_length=1000)),
                ('index', models.IntegerField(default=0)),
                ('can_evolve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
